multitenancy_enabled: false

server:
  http_listen_port: 9009
  log_level: info

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /data/blocks

ingester:
  ring:
    replication_factor: 1

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /data/blocks
  tsdb:
    dir: /data/tsdb

compactor:
  data_dir: /data/compactor

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /data/rules

alertmanager_storage:
  backend: filesystem
  filesystem:
    dir: /data/alertmanager

limits:
  ingestion_rate: 100000
  ingestion_burst_size: 200000
